trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    wget https://releases.hashicorp.com/terraform/1.12.2/terraform_1.12.2_linux_amd64.zip
    unzip terraform_1.12.2_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
    terraform version
  displayName: 'Install Terraform'

- task: AzureCLI@2
  displayName: Terraform Init
  inputs:
    azureSubscription: 'terraform-sc'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      terraform init

- task: AzureCLI@2
  displayName: Terraform Init
  inputs:
    azureSubscription: 'terraform-sc'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az account show
      terraform init

- script: terraform validate
  displayName: 'Terraform Validate'

- script: terraform plan
  displayName: 'Terraform Plan'